site_name: bikes
site_description: Bike repair tracking for HUBS Coop
repo_url: https://github.com/drewbrew/hubs-bikes
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/drewbrew">drewbrew</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
