# Generated by Django 3.1.5 on 2021-02-22 23:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("bikes", "0002_auto_20210128_1613"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address_line_1", models.CharField(blank=True, max_length=100)),
                ("address_line_2", models.CharField(blank=True, max_length=100)),
                ("address_line_3", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=2)),
                ("zip", models.CharField(blank=True, max_length=20)),
                ("phone", models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name="bike",
            name="condition",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (10, "10 (like new)"),
                    (9, "9"),
                    (8, "8"),
                    (7, "7"),
                    (6, "6"),
                    (5, "5"),
                    (4, "4"),
                    (3, "3"),
                    (2, "2"),
                    (1, "1 (worst)"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bike",
            name="dismantled_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bike",
            name="intake_time",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="bike",
            name="marked_as_needing_repair_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bike",
            name="marked_as_ready_for_sale_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bike",
            name="marked_as_ready_for_scrap_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bike",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="bike",
            name="refurb_parts_used",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="bike",
            name="sold_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bike",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("needs_repair", "Needs Repair"),
                    ("ready_for_sale", "Ready For Sale"),
                    ("sold", "Sold"),
                    ("ready_to_scrap", "Ready To Scrap"),
                    ("dismantled", "Dismantled"),
                    ("earned", "Earned"),
                    ("added_to_fleet", "Added To Fleet"),
                ],
                default="new",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="bike",
            name="donated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bikes_donated",
                to="bikes.donor",
            ),
        ),
    ]
